import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import { Anton, Barlow, Geist } from "next/font/google";
import Footer from "@/components/Footer";
import SmoothScroll from "@/components/SmoothScroll";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
});
const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose what you need
});

export const metadata: Metadata = {
  title: " Gmans Internationals | Premium Denim Manufacture   ",
  description: "Generated by create next app",
  icons: {
    icon: "https://cdn.prod.website-files.com/65b78ba82104f6788b2a990f/65b7a313b2c07d242b833ffb_Vector%20(1).svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", anton.className, barlow.className, "font-sans", geist.variable)}
    >
      <body className="min-h-full max-w-screen flex flex-col ">
        <Navbar />
        <SmoothScroll>{children}</SmoothScroll>

        <Footer />
      </body>
    </html>
  );
}
